services:
  app:
    build:
      context: .
      dockerfile_inline: |
        FROM ruby:3.3.6-bookworm

        RUN apt-get update && \
          apt-get install -y --no-install-recommends ghostscript
        RUN sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml

        WORKDIR /var/lib/redmine
        RUN git clone --depth=1 https://github.com/redmine/redmine .

        ENV BINDING="0.0.0.0"
        EXPOSE 3000

        COPY entrypoint.sh /
        RUN chmod +x /entrypoint.sh
        ENTRYPOINT ["/entrypoint.sh"]
        CMD ["bin/rails", "server", "-b", "0.0.0.0"]

    image: redmine
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - localstack
      - selenium
    tty: true
    volumes:
      - bundle:/usr/local/bundle
      - ./:/var/lib/redmine/plugins/redmica_s3
      - ./tmp/screenshots:/var/lib/redmine/tmp/screenshots
    environment:
      AWS_REGION: ap-northeast-1
      CAPYBARA_SERVER_HOST: app
      CAPYBARA_SERVER_PORT: 3000
      GOOGLE_CHROME_OPTS_ARGS: headless,disable-gpu,no-sandbox,disable-dev-shm-usage
      SELENIUM_REMOTE_URL: http://selenium:4444/wd/hub

    healthcheck:
      test: ["CMD", "bin/rails", "db:migrate:status"]
      interval: 30s
      timeout: 5s
      retries: 3

  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - bucket.s3.localhost.localstack.cloud

  selenium:
    restart: "no"
    image: selenium/standalone-chrome
    platform: linux/amd64

volumes:
  bundle:
